/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js. It is checked in so package-local
// typechecking works before the first local `next build`.
